title: Ralph Gonzalvo
author:
  name: Ralph Gonzalvo
  url: https://github.com/RalphGonzalvo

description: >-
  Software Engineer in Japan. Building cool things. Always developing random ideas.

remote_theme: jekyll/minima@1e8a445

minima:
  skin: dark
  social_links:
    - { title: "GitHub", url: "https://github.com/RalphGonzalvo", icon: "github" }
  navigation:
    - title: "Projects"
      url: "/projects/"
    - title: "About"
      url: "/about/"

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
