title: Ralph Gonzalvo
author:
  name: Ralph Gonzalvo
  url: https://github.com/RalphGonzalvo

description: >-
  Software Engineer in Japan. Building cool things. Always developing random ideas.

minima:
  skin: dark
  social_links:
    - { title: "GitHub", url: "https://github.com/RalphGonzalvo", icon: "github" }
  hide_site_feed_link: true

plugins:
  - jekyll-seo-tag

include:
  - assets
